parameters:
- name: subscription
  displayName: Scopes
  type: string
  default: regression
  values:
  - smoke
  - regression

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - main

trigger:
- main

pool:
   vmImage: 'windows-latest'

steps:
- task: replacetokens@3
  displayName: 'Replace tokens'
  inputs:
    targetFiles: |
      **/credentials.json
    tokenPrefix: '$('
    tokenSuffix: ')'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true
    architecture: 'x64'

- script: |
- task: CmdLine@2
  inputs:
    script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: CmdLine@2
  inputs:
    ${{ if contains(parameters.subscription, 'smoke') }}:
      script: |
        pytest -k "smoke" --junitxml=result.xml -o junit_family="xunit1"
    ${{ if contains(parameters.subscription, 'regression') }}:
      script: |
        pytest --junitxml=result.xml -o junit_family="xunit1"
  displayName: 'Pytest'
  continueOnError: true

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'result.xml'
